export const bestSelerServer = [
    {
        "id": 1,
        "name": "ChargeWorx Folding",
        "link": "ChargeWorx_Folding",
        "prise": 70,
        "newPrise": 50,
        "img": "/img/product/ChargeWorx_Folding.jpg",
    },
    {
        "id": 2,
        "name": "Clear Case With MagSafe",
        "link": "Clear_Case_With_MagSafe",
        "prise": null,
        "newPrise": 50,
        "img": "/img/product/Clear_Case_With_MagSafe.jpg",
    },
    {
        "id": 3,
        "name": "HDMI Multiport Adapter",
        "link": "HDMI_Multiport_Adapter",
        "prise": 20,
        "newPrise": 12,
        "img": "/img/product/HDMI_Multiport_Adapter.jpg",
    },
    {
        "id": 4,
        "name": "Mighty Mini 130 30W",
        "link": "Mighty_Mini_130_30W",
        "prise": 30,
        "newPrise": 22,
        "img": "/img/product/Might_Mini_130_30W.jpg",
    },
    {
        "id": 5,
        "name": "PowerBox 160 US",
        "link": "PowerBox_160_US",
        "prise": null,
        "newPrise": 25,
        "img": "/img/product/PowerBox_160_US.jpg",
    },
    {
        "id": 6,
        "name": "Premium World Power",
        "link": "Premium_World_Power",
        "prise": null,
        "newPrise": 21,
        "img": "/img/product/Premium_World_Power.jpg",

    },
    {
        "id": 7,
        "name": "Thin Case For IPhone",
        "link": "Thin_Case_For_IPhone",
        "prise": 75,
        "newPrise": 65,
        "img": "/img/product/Thin_Case_For_IPhone.jpg",
    },
    {
        "id": 8,
        "name": "Thin Smartphone Case",
        "link": "Thin_Smartphone_Case",
        "prise": 105,
        "newPrise": 80,
        "img": "/img/product/Thin_Smartphone_Case.jpg",
    }
]