export const ProductServer = [
    {
        "id": "1",
        "name": "ChargeWorx Folding",
        "prise": 70,
        "newPrise": 50,
        "grade": 3.8,
        "cart_img": ["/img/product/ChargeWorx_Folding.jpg", "/img/product/ChargeWorx_Folding_2.jpg", "/img/product/ChargeWorx_Folding_3.jpg", "/img/product/ChargeWorx_Folding_4.jpg"],
    },
    {
        "id": "2",
        "name": "Clear Case With MagSafe",
        "prise": null,
        "newPrise": 50,
        "grade": 5,
        "cart_img": ["/img/product/Clear_Case_With_MagSafe.jpg", "/img/product/15W_Wireless_Charging_1.jpg", "/img/product/15W_Wireless_Charging_2.jpg", "/img/product/15W_Wireless_Charging_3.jpg"],
    },
    {
        "id": "3",
        "name": "HDMI Multiport Adapter",
        "prise": 20,
        "newPrise": 12,
        "grade": 4.2,
        "cart_img": ["/img/product/HDMI_Multiport_Adapter.jpg"],
    },
    {
        "id": "4",
        "name": "Mighty Mini 130 30W",
        "prise": 30,
        "newPrise": 22,
        "grade": 1.9,
        "cart_img": ["/img/product/Might_Mini_130_30W.jpg"],
    },
    {
        "id": "5",
        "name": "PowerBox 160 US",
        "prise": null,
        "newPrise": 25,
        "grade": null,
        "cart_img": ["/img/product/PowerBox_160_US.jpg"],
    },
    {
        "id": "6",
        "name": "Premium World Power",
        "prise": null,
        "newPrise": 21,
        "grade": null,
        "cart_img": ["/img/product/Premium_World_Power.jpg"],

    },
    {
        "id": "7",
        "name": "Thin Case For IPhone",
        "prise": 75,
        "newPrise": 65,
        "grade": 4.4,
        "cart_img": ["/img/product/Thin_Case_For_IPhone.jp"],
    },
    {
        "id": "8",
        "name": "Thin Smartphone Case",
        "prise": 105,
        "grade": null,
        "cart_img": ["/img/product/Thin_Smartphone_Case.jpg"],
    }
]