export const ProductServer = [
    {
        "id": "1",
        "link": "ChargeWorx_Folding",
        "name": "ChargeWorx Folding",
        "prise": 70,
        "newPrise": 50,
        "grade": 3.8,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/ChargeWorx_Folding.jpg", "/img/product/ChargeWorx_Folding_2.jpg", "/img/product/ChargeWorx_Folding_3.jpg", "/img/product/ChargeWorx_Folding_4.jpg"],
        "soldInTwelveHours": 12,
        "remainder": 20,
    },
    {
        "id": "2",
        "name": "Clear Case With MagSafe",
        "link": "Clear_Case_With_MagSafe",
        "prise": null,
        "newPrise": 50,
        "grade": 5,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/Clear_Case_With_MagSafe.jpg", "/img/product/15W_Wireless_Charging_1.jpg", "/img/product/15W_Wireless_Charging_2.jpg", "/img/product/15W_Wireless_Charging_3.jpg"],
        "soldInTwelveHours": 3,
        "remainder": 140,
    },
    {
        "id": "3",
        "name": "HDMI Multiport Adapter",
        "link": "HDMI_Multiport_Adapter",
        "prise": 20,
        "newPrise": 12,
        "grade": 4.2,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/HDMI_Multiport_Adapter.jpg"],
        "soldInTwelveHours": 18,
        "remainder": 10,
    },
    {
        "id": "4",
        "name": "Mighty Mini 130 30W",
        "link": "Mighty_Mini_130_30W",
        "prise": 30,
        "newPrise": 22,
        "grade": 1.9,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/Might_Mini_130_30W.jpg"],
        "soldInTwelveHours": 5,
        "remainder": 25,
    },
    {
        "id": "5",
        "name": "PowerBox 160 US",
        "link": "PowerBox_160_US",
        "prise": null,
        "newPrise": 25,
        "grade": 0,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/PowerBox_160_US.jpg"],
        "soldInTwelveHours": 9,
        "remainder": 9,
    },
    {
        "id": "6",
        "name": "Premium World Power",
        "link": "Premium_World_Power",
        "prise": null,
        "newPrise": 21,
        "grade": 0,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/Premium_World_Power.jpg"],
        "soldInTwelveHours": 155,
        "remainder": 3,
    },
    {
        "id": "7",
        "name": "Thin Case For IPhone",
        "link": "Thin_Case_For_IPhone",
        "prise": 75,
        "newPrise": 65,
        "grade": 4.4,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/Thin_Case_For_IPhone.jp"],
        "soldInTwelveHours": 1,
        "remainder": 28,
    },
    {
        "id": "8",
        "name": "Thin Smartphone Case",
        "link": "Thin_Smartphone_Case",
        "prise": 105,
        "newPrise": 25,
        "grade": 0,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/Thin_Smartphone_Case.jpg"],
        "soldInTwelveHours": 0,
        "remainder": 105,
    },
    {
        "id": "9",
        "name": "Waterproof Wireless Charging",
        "link": "Waterproof_Wireless_Charging",
        "prise": 34,
        "newPrise": 22,
        "description": "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these books, you won’t be able to put them down.",
        "cart_img": ["/img/product/Waterproof_Wireless-Charging.jpg"],
        "soldInTwelveHours": 31,
        "remainder": 2,
    }
]